name: todos
description: "bloc state todos app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  bloc_test: ^10.0.0
  mockingjay: ^1.0.0
  mocktail: ^1.0.4
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository
  json_annotation: ^4.9.0
  meta: ^1.16.0
  ulid: ^2.0.1
  build_runner: ^2.4.15
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true

