name: todos_api
description: The interface and models for an API providing access to todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
  # build_runner: ^2.4.15
  # json_serializable: ^6.9.4
  
dependencies:
  build_runner: ^2.4.15
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  meta: ^1.16.0
  uuid: ^4.5.1
